Enable 'fc' as transport for blktests
osandov/blktests pull request #100
Opened 2022-08-30 10:08 UTC by hreinecke

Hi all,

this patchset adds support for the 'fc' transport in blktests by configuring the 'fcloop' device. This allows to validate the nvme-fc transport in addition to the existing 'loop', 'tcp', and 'rdma' transports.

2022-08-30 10:09 UTC, hreinecke commented
Note that 'fcloop' currently has some issues, as it'll retry authentication failures, causing repeated connect/disconnect attempts to fail. Patch is pending in the linux-nvme mailing list ('nvme-auth: retry command if DNR bit is not set').

2022-08-30 12:52 UTC, hreinecke commented
Patchset submitted to linux-nvme, thread 'nvme: honor DNR status for authentication' to fix the connect behaviour wrt DNR bit handling.

2022-09-06 12:30 UTC, kawasaki requested changes
Thanks for the PR. As github CI reported, [shellcheck has some complaints](https://github.com/osandov/blktests/runs/8092181659?check_suite_focus=true). Could you fix them?
Also I made a few minor nit comments. 
I ran NVME test group with nvme_trtype=fc and result looks ok for me.

2022-09-06 12:30 UTC, kawasaki commented on tests/nvme/rc
> +		if [[ "${trtype}" == "fc" ]] ; then
A nit: I think indent level of this part can be shallower:

```
if [[ "${trtype}" == "fc" ]] ; then
  ...
elif [[ "${trtype}" != "loop" ]]; then
  ...
fi
```

2022-09-06 12:30 UTC, kawasaki commented on tests/nvme/rc
> +		if [[ "${trtype}" = "fc" ]]; then
Same nit comment as above.

2022-09-06 12:30 UTC, kawasaki commented on tests/nvme/rc
> +	if [[ "${trsvcid}" ]]; then
If we change this condition check as follows, previous hunk is not required, I think:

```
if [[ "${adfram}" != "fc" ]]; then
```

2023-01-30 07:10 UTC, kawasaki commented
@igaw created another PR #108 as v2. I close this PR.

2023-01-30 07:10 UTC, closed without merging