block/022: skip test when only 1 cpu available
osandov/blktests pull request #75
Opened 2020-10-09 13:59 UTC by liangxiao1

Blow is fail log in single cpu node.
block/022 (Test hang caused by freeze/unfreeze sequence)     [failed]
    runtime    ...  30.138s
    --- tests/block/022.out	2020-10-09 12:43:48.000000000 +0000
    +++ /usr/local/blktests/results/nodev/block/022.out.bad	2020-10-09 13:45:18.594417401 +0000
    @@ -1,2 +1,3 @@
     Running block/022
    +taskset: failed to set pid 13212's affinity: Invalid argument
     Test complete

Signed-off-by: Xiao Liang <xiliang@redhat.com>

2022-05-16 01:56 UTC, kawasaki requested changes
In the commit message, the word "Blow" looks spell mistake. Did you mean "Below"?
Also, needs conflict resolution to be merged to latest master branch.

2022-05-16 01:58 UTC, kawasaki commented
As reported by @liangxiao1, I confirmed that the test case block/022 fails on single CPU node using latest blktests master branch. I think this pull request worth merging upstream.

2022-05-16 02:23 UTC, liangxiao1 commented
Thanks, @kawasaki 
Apologize for typo in commit log.

2022-05-30 00:53 UTC, kawasaki approved these changes
I have merged the commit manually. I fixed the commit message typo and resolved a merge conflict.

2022-05-30 00:54 UTC, kawasaki commented
Thanks for this PR. I close this.

2022-05-30 00:54 UTC, closed without merging