loop: Add test to setup GPT and ESP on raw disk image (regression test for commit b9684a71fca7)
osandov/blktests pull request #93
Opened 2022-06-09 07:08 UTC by michael-schaller

Add test for setting up a raw disk image with a GPT and ESP. This is a regression test for commit b9684a71fca7 ("block, loop: support partitions without scanning").

Signed-off-by: Michael Schaller <misch@google.com>

2022-06-10 11:23 UTC, kawasaki requested changes
Hi @michael-schaller 
Thank you for this PR. The code logic looks good. Let me make a few comments on other things.

-  Apache license is noted in the file header comment. However, GPL3+ is the license for blktests (some files have GPL2+). To keep license of blktests simple, I wish to see GPL3+ for this new test case also.
- The commit title is rather lengthy. The additional note in parenthesis (regression ...) can be removed, I think.
- The line of commit message is too long. I wish to see 72 characters each in the commit message lines.

Hope these requests are reasonable for you.

2022-06-13 09:34 UTC, michael-schaller commented
Done. Please take another look.

2022-06-14 07:27 UTC, kawasaki commented
@michael-schaller Thanks for the license change! However, the 2nd commit for license change does not have your Signed-off-by tag, which all blktests commits have. Could you add the tag?

Also, single commit is the better record than the two commits. Could you squash the two commits into one and force push to your git branch? Or if it takes too much time for you, please let me know. I can do that squash work.

2022-06-15 06:00 UTC, michael-schaller commented
Done. Please take another look.

2022-06-15 09:04 UTC, merged

2022-06-15 09:05 UTC, kawasaki commented
@michael-schaller Thanks for the updates. Applied to the master branch.

2022-06-21 07:56 UTC, michael-schaller commented
Thanks. :smiley: